### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Abcold** [dappuniversity/nft#5]
Compiling your contracts...
===========================
Error: Unsupported compiler: optimizer
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:28:1
    at Array.map (<anonymous>)
    at compile (/usr/local/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:26:1)
    at Object.compile (/usr/local/lib/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:68:47)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/compile.js:75:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:183:1)
Truffle v5.4.22 (core: 5.4.22)
Node v14.17.6

i try to fix in  truffle-config.js , like this: 
compilers: {
    solc: {
        version: "^0.5.0"  ,
    },
      optimizer: {
        enabled: true,
        runs: 200
      },
  },
but still failed, what should i do?

**Comment by Abcold** [comment]
i fixed this issue , 
i change pragma in  color.sol :
pragma solidity 0.5.16;
